### ISSUE TITLE
Potential bug with likert function

### ISSUE THREAD

**Issue by monsoontrader** [jbryer/likert#11]
Hi,

New to the 'likert' package (very good BTW). I am getting an error when using the likert() function on a dataset:

Error in likert(website) : 
  All items (columns) must have the same number of levels\

The problem seems to be that I have one response vector without a 'Disagree' response from at least one subject.

Is there are work around for this problem?

Any help appreciated.

Cheers.

**Comment by donniemeyer32085** [comment]
Thought I'd give an answer to this. For me, my levels were the same. I had my data as a tibble, when I changed it to a data.frame it worked.

**Comment by fmannhardt** [comment]
Thanks that was very helpful, indeed `likert` seems to not work with `tibble`. 
I think this should be reopened, or adressed in #85

**Comment by jbryer** [comment]
Version 2.0 will handle tibles better. However, my stance is that the
likert package is designed to work with data.frames, tibbles are not
data.frames.

**Comment by fmannhardt** [comment]
Thanks. A better error message would already be helpful since only finding this issue prevented me from wasting a lot of time on finding the cause for the problem.

**Comment by liberrenaud** [comment]
Hello @jbryer - First awesome package - thanks a mill! I had a similar issue due to fact that I was working with Tibble. As per @fmannhardt comment - if the error would first mention that data.frame need to be used rather that tibble - instead of getting the `Error in likert(prep_likert) : 
  All items (columns) must have the same number of levels` it would make things clearer - anyway thanks for releasing such a cool package!

**Comment by kransom14** [comment]
I also had this same issue and converting to data frame fixed it. I would not have been able to solve it had I not found this thread.

**Comment by RaymondLTremblay** [comment]
For me it does not solve the problem, I have five levels for 3 items in a data frame. I checked and they are coded as factors.   So I'm lost to what is the next step.....

**Comment by jbryer** [comment]
If is.tibble returns true, they try as.data.frame before calling likert.
Also make sure that levels(mydf$col) is the same for all three items.

**Comment by joesephx2** [comment]
Hi jbryer, thanks for making likert available.  I am new to R, so please be patient with me.  liberrenaud comments resolve my issue with the same error message. For others R novices out there, I like to make following suggestions for your considerations:
1. Another exception handling message for wrong type
2. checking all class type outputs (please see the following R output)

> likert(tmp)
Error in likert(tmp) : 
  All items (columns) must have the same number of levels
> class(tmp)
[1] "tbl_df"     "tbl"        **"data.frame"**

Thank you

**Comment by jbryer** [comment]
You need to convert the tibble to a data.frame first.

tmp <- as.data.frame(tmp)

**Comment by agilebean** [comment]
> You need to convert the tibble to a data.frame first. tmp <- as.data.frame(tmp)

@jbryer I totally get you but IMHO the error message for using a tibble is quite misleading.
I had to search a bit to understand that the error thrown is wrong:
```
Error in likert(.) : 
  All items (columns) must have the same number of levels
```
Can you please change this error message just to include a hint that tibbles are not supported?
Or, as the tidyverse become increasingly standard for tutorials, include the handling of tibbles?
This would greatly improve beginners' user experience and increase adoption of your otherwise great package...

**Comment by jbryer** [comment]
The error thrown is not wrong. I appreciate that as a beginner that is
learning through the tidyverse point-of-view this is frustrating, however
tibbles have broke the base R system. I do check that the object passed in
is a data.frame using the is.data.frame function. The problem is tibbles
return TRUE for this function, but do not behave as data.frames. Please
file a bug with the tibble group indicating that if is.data.frame is to
return TRUE, it should behave as a data.frame. In this instance,
mydataframe[,1] should return a vector, not another tibble.

**Comment by Generalized** [comment]
**I strongly support** the kind request to at least **print a message with a possible reason,** like

> "All items (columns) must have the same number of levels.
> Suggestion: if your data are stored in a 'tibble' (part of Tidyverse), cast it to a regular data.frame first."
> 

This would save A LOT of time! The default error led me to modification of question columns (make them factors with equal list of levels), investigating them... totally misleading and a serious waste of time. With this small suggestion people would immediately understand the issue and fix it.

**Comment by Aleinvarg** [comment]
i solve the issue entering a line setting the imput as data frame
LIKERT_1 <- as.data.frame(df)
