### ISSUE TITLE
error in likert(…, grouping = grouping)

### ISSUE THREAD

**Issue by andreaphsz** [jbryer/likert#16]
likert() throws an error, if there is a variable with unused levels, and grouping is used.

```
library(likert)
library(reshape)

df <- data.frame(matrix(c(1,1,1,1,2,1,2,2), 4))

df[,1] <- factor(df[,1], 1:2)
df[,2] <- factor(df[,2], 1:2)

gr <- c(1,1,2,2)

likert(df, grouping=gr, nlevels=2)
```

output is:

```
Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
```

**Comment by patilv** [comment]
I am having the same problem show up and the example in the demo is also throwing the same error.

**Comment by josiahpjking** [comment]
Not sure why, but detaching the reshape package solved this for me.

**Comment by jbryer** [comment]
I just recently updated the package to use reshape2 instead of reshape given that ggplot2 uses the latter now. I do explicitly call reshape2::melt but if reshape is also loaded, there is a conflict somewhere in the namespace. I believe it has to do with the fact that the class type returned by both are the same so the wrong S3 method is being dispatched. My advice, abandon reshape and stick with reshape2. I believe that RStudio and Hadley have done.

**Comment by patilv** [comment]
Detaching reshape did it for me as well. Thanks for the tip.  I believe the reshape2 tasks are now predominantly going to be done using tidyr. So we could go to the gather function to do what melt does. I will take a closer look at the package code sometime soon. Thanks for the great work on this.

**Comment by jbryer** [comment]
Great! Glad it worked. I finally get around to update to reshape2 and
Hadley has another way of doing things. ;-)

-Jason

**Comment by raynamharris** [comment]
Thanks! I detached reshape then loaded reshape2 and all was well

detach("package:reshape", unload=TRUE)
library("reshape2")
