### ISSUE TITLE
Way of storing full question names

### ISSUE THREAD

**Issue by houshuang** [jbryer/likert#6]
In the example, you rename the variables like this:

```
items24 <- rename(items24, c(
        ST24Q01="I read only if I have to.",
        ST24Q02="Reading is one of my favorite hobbies.",
        ST24Q03="I like talking about books with other people.",
        ST24Q04="I find it hard to finish books.",
        ST24Q05="I feel happy if I receive a book as a present.",
        ST24Q06="For me, reading is a waste of time.",
        ST24Q07="I enjoy going to a bookstore or a library.",
        ST24Q08="I read only to get information that I need.",
        ST24Q09="I cannot sit still and read for more than a few minutes.",
        ST24Q10="I like to express my opinions about books I have read.",
        ST24Q11="I like to exchange books with my friends."))
```

This works, but I find it very messy to include all this information in my code. As well, since some of the questions contain special characters that R won't accept (ie. Likert will still work, but I can no longer do q$Weird question with lot's of characters?), I will have to redo this if I extract a new set of variables, a different grouping etc.

To me, it would be much cleaner if I could somehow store the full question names in the data frame, perhaps as a comment on each column, or as a metadata attribute? Usually the way I work with questionnaire data is to write one script to clean it up (convert to NAs, order factors, etc), save the data, and then use knitr to load the data and write the report. It would be great if I could store the question names in the first script, and then easily say "show  me a likert graph of these five variables", and it would have the right names etc.

I've also been thinking of better ways of storing and sharing data than CSV - how do you attach metadata on short/full variable names, ordered factors, NAs etc... That's a further step, but for now some meta info that I could store in an Rdata would be a great first step.

Thanks for a great package!

**Comment by rdstern** [comment]
@jbryer I am re-opening this issue as I also felt it would be better to store the questions within the data frame.
This is conveniently done in a data frame, by using the variable labels.  Here is an example with one of your data sets.

[mass_likert.zip](https://github.com/user-attachments/files/24470031/mass_likert.zip)


I like the data sets you provide.  Would it also be possible to add the raw data for this maths set?  It is easy to get from your demo, but would be even more convenient if available as another data example.  

In making use of the variable labels, I note that a competing function, gglikert,  uses the variable labels, when they exist, and otherwise uses the names.  Hence adding this feature would need changes in the function, but not necessarily in the arguments when you make your likert object.  Alternatiovely you could have a labels argument, with default TRUE to use labels when they exist.  If set to FALSE, then it ignores the variable labels.
 

I now realise I didn't have permission to reopen an issue, so am just commenting!
