### ISSUE TITLE
sum of percentages higher than 100% in likert bars 

### ISSUE THREAD

**Issue by verajosemanuel** [jbryer/likert#80]
it's due to rounding float numbers. Please allow disable rounding or specify digits to round.

![rounding](https://user-images.githubusercontent.com/15836677/32384711-0ffb8af4-c0bc-11e7-9158-0d005323baff.PNG)
```

df <- data.frame(
  Item = c("question1",
           "question2",
           "question3"),
  very_bad = c(0.649350649350649, 5.19480519480519,
               2.5974025974026),
  bad = c(7.14285714285714, 12.3376623376623,
          1.94805194805195),
  neutral = c(11.6883116883117, 9.09090909090909,
              5.84415584415584),
  good = c(42.8571428571429, 35.7142857142857,
           22.0779220779221),
  very_good = c(37.6623376623377, 37.6623376623377,
                67.5324675324675)
)

# totals are 100%
no.rounding <- df %>% group_by(Item) %>% mutate(total = sum(very_bad,bad,neutral,good,very_good))

good.rounding <- df %>% group_by(Item) %>% mutate(total = round(sum(very_bad,bad,neutral,good,very_good)))

# totals are 101%   ----------------------------------------------------------------
bad.rounding <- df %>% group_by(Item) %>% mutate(total = sum(round(very_bad,0),round(bad,0),round(neutral,0),round(good,0),round(very_good,0)))



```

**Comment by FranIL** [comment]
Did anyone solve this problem??
Thanks!!

**Comment by verajosemanuel** [comment]
This package is abandoned. Owner seems that is not working on it anymore. I recommend to use plain simple ggplot2. A simple search in google gives you several usable examples.

https://www.google.es/search?q=ggplot+likert+chart&ie=UTF-8&oe=UTF-8&hl=es-es&client=safari

**Comment by FranIL** [comment]
Ok, thank you for the information.

**Comment by XJERL** [comment]
Damn, I have the same problem, so it might have no sollution, this sucks!!!

**Comment by jbryer** [comment]
I have added a digits parameter to the plot function that is passed through to the format function. You need to reinstall from Github.

**Comment by XJERL** [comment]
Sorry J., but can you upload an example, I've tried different ways to use format function with the plot function, and I see no solution. The "results" object of the likert function seems to have the percentages with a sufficent number of digits, you can control its number with the format function "format(likert$results, digits = n), but the problem is the plot function, that rounds the percentage again to integers again.  How do you pass the format function, inside the plot function; i think this should be simpler, like: plot(likertobject, digits = n), just as you have added the so many others parameters. If I use the format function, as a parameter, inside the plot function, I must specify the x object over wich the digits parameter is applied, but that way I get no results. Can you give us an example.
As I told you I'm using the plot function in the simplest way possible:
plot(likertobject)

**Comment by XJERL** [comment]
Hi, by the way "digits" works just fine with the "heat" plot type, but nothing with "bar", which is the type I'm using. So any solution or example of how to use the format function that you're said?
Greetings.

**Comment by jbryer** [comment]
Parameters are now passed through on the bar plot verison.

**Comment by XJERL** [comment]
Hi J., but I don't get what you say:
My code
`plot(likert(lik_carac,
            grouping = df$Indique.el.rango.de.su.edad),
     type = "bar",
     digits = 3,
     plot.percents = TRUE,
     plot.percent.high = FALSE,
     plot.percent.low = FALSE)`
My output:
![rplot](https://user-images.githubusercontent.com/11275380/53904222-2ae55000-400b-11e9-9bdb-7a07dbf7129f.jpeg)
I see no "3 digits".

**Comment by jbryer** [comment]
Did you reinstall?

**Comment by XJERL** [comment]
Yep,

Skipping install of 'likert' from a github remote, the SHA1 (5bf9b1eb) has not changed since last install.
  Use `force = TRUE` to force installation
I'll  force it, maybe restarting R Studio.

**Comment by XJERL** [comment]
So J., still nothing. Don't know, maybe some minor change not done in the previous revision.
Thnks,
Greetings.

**Comment by XJERL** [comment]
Issue solved, Thnks J., superb library so far!!!
