### ISSUE TITLE
Limiting digits in likert heat map

### ISSUE THREAD

**Issue by DiscoveriesinData** [jbryer/likert#98]
I don't understand why my heatmap is rendering with so many digits, nor how to limit those digits in a likert() object.

![capture](https://user-images.githubusercontent.com/29905051/47759360-7dcd8600-dc6c-11e8-8ee6-5202467ef5b3.PNG)

**Comment by jbryer** [comment]
This is the default for ggplot2.

**Comment by jbryer** [comment]
A quick google search suggests not. Not sure how to handle this within the
likert framework. You might have to change the implementation manually to
call round before geom_text. The source code is here:
https://github.com/jbryer/likert/blob/master/R/plot.likert.heat.r

**Comment by XJERL** [comment]
I have the opposite problem. I want to display more digits in the percentages, because, even I understand the sums of rounding percentages might not match with 100%, the people who is reading a report might not understand why there is a missing 1 %. So, my issue is, how do I increase the number of digits in the likert plot?
Greetings

**Comment by jbryer** [comment]
I have added a digits parameter to control how many digits are printed for heatmaps.
